package lab21.model;

import org.springframework.data.annotation.Id;

/*
 * This class is used to transfer data to/from doctor templates
 *  for registering new doctor and updating doctor profile.
 */
public class Doctor {
	
	@Id
	private int id;   // unique id generated by database.
	private String lastName;
	private String firstName;
	private String specialty;
	private String practice_since_year;  // yyyy  The year doctor started in practice.
	private String ssn;
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getSpecialty() {
		return specialty;
	}
	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}
	public String getPractice_since_year() {
		return practice_since_year;
	}
	public void setPractice_since_year(String practice_since_year) {
		this.practice_since_year = practice_since_year;
	}
	public String getSsn() {
		return ssn;
	}
	public void setSsn(String ssn) {
		this.ssn = ssn;
	}
	@Override
	public String toString() {
		return "Doctor [id=" + id + ", lastName=" + lastName + ", firstName=" + firstName + ", specialty="
				+ specialty + ", practice_since_year=" + practice_since_year + ", ssn=" + ssn + "]";
	}
}
